### ISSUE TITLE
.dat import fails for lipsync, fix included in comment

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/mhx2-makehuman-exchange#4]
error on importing .dat file from papagayo for lipsync.
I am not a programmer, but was able to hack through and solve the problem
in the file visemes.py, change line 180 from
`context.scene.objects.active = rig`

to line 180
`rig = bpy.context.scene.objects[0]`
and insert a new line 181 with
`bpy.context.view_layer.objects.active = rig`

this fixes the inability to import the .dat file.
I have never looked into pull requests, or how to really use github properly, so i am just entering the fix here. hope that, that fix does'nt break something else.
Thank you all for your valuable work!

**Comment by Aranuvir** [comment]
The line "rig = bpy.context.scene.objects[0]" doesn't really make sense. The result for rig could be anything like the default cube, camera or lamp. IMHO id should also work with only the second line. Could you test this with only "context.view_layer.objects.active = rig" ? I don't have data to test.

**Comment by Hunanbean** [comment]
You are correct. the line
`rig = bpy.context.scene.objects[0]`
seems to be entirely unnecessary. I removed it, and left the only change as line 180 now being
`context.view_layer.objects.active = rig`
and it is working. It continues to work with or without the `bpy.` in front of `context`
Again, i have literally no understanding of python, it was just pure luck and searches through community knowledge that allowed me to change the code in the first place. Thank you for seeing the error, and understanding what it all means. be well!

**Comment by Aranuvir** [comment]
>Again, i have literally no understanding of python

That's why a wrote a little explanation. Thanks for fixing anyway :).
